### ISSUE TITLE
[question] tiling window extension?

### ISSUE THREAD

**Issue by ivotron** [rbreaves/sorun#27]
i was wondering if a tiling window gnome extension can be used with the sorun config, and what would that be. any tips would be greatly appreciated! 🙏 

edit: I meant using a gnome extension for tiling windows, rather than using a tiling DE such as i3

**Comment by rbreaves** [comment]
I have some configs for doing this with XFCE actually, but I don't think I have yet added anything XFCE related to this project. In theory though the same Zentile project (I use them for xfce) could be used for any DE as far as I know.

https://github.com/blrsn/zentile

This script targets Budgie - although a gnomeshell does appear to be running still, the panel is replaced with Budgie though & it appears that gnome extensions are shut off. I've been looking at the text files recently that setup the initial budgie config, so maybe you can re-enable gnome extensions, no idea if they'd actually work. discourse.ubuntubudgie.org might be your best bet as fossfreedom can answer a lot of questions as well.

I haven't focused on Pop_OS! for a little while - as my first goal is polish up Ubuntu Budgie, then XFCE and then I would come back to Pop_OS! at some point. I might actually get back to elementaryOS first, I hear there's a good fork of their wingpanel with a global menu now. A lot of changes are happening in the dev branch though - I believe I will be knocking out some really important features to get done relatively soon.

**Comment by ivotron** [comment]
thanks a lot for the explanation! I think I'll give zentile a try and see how it goes. I'll report back on results. thanks! 🙏
